version: '3'
services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql:5.7
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - /data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=scrum"
    network_mode: "bridge"

  java-demo-scrum:
    container_name: java-demo-scrum
    image: demo
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    network_mode: "bridge"
    depends_on:
      - docker-mysql
    links:
      - docker-mysql:mysql